# Generated by Django 4.2.6 on 2023-10-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='feaured',
            new_name='featured',
        ),
    ]
